# Generated by Django 6.0.4 on 2026-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0009_alter_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.product'),
        ),
    ]
