# Generated by Django 6.0.4 on 2026-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه'), ('unisex', 'Unisex')], default='Male', max_length=20),
        ),
    ]
