# Generated by Django 6.0.4 on 2026-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه')], default='male', max_length=10),
        ),
    ]
