# Generated by Django 6.0.4 on 2026-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_brand_remove_product_brand_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/'),
        ),
    ]
